
-- Create poshak_seva_bookings table if it doesn't exist
CREATE TABLE IF NOT EXISTS poshak_seva_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    seva_date DATE NOT NULL,
    poshak_type TEXT NOT NULL,
    occasion TEXT,
    additional_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'pending',
    payment_status TEXT DEFAULT 'unpaid',
    admin_notes TEXT
);

-- Add comment to the table
COMMENT ON TABLE poshak_seva_bookings IS 'Stores bookings for Poshak Seva';

-- Set up Row Level Security
ALTER TABLE poshak_seva_bookings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS poshak_seva_anonymous_insert_policy ON poshak_seva_bookings;
DROP POLICY IF EXISTS poshak_seva_user_select_policy ON poshak_seva_bookings;
DROP POLICY IF EXISTS poshak_seva_admin_policy ON poshak_seva_bookings;

-- Create policies
-- Policy for anyone to insert bookings
CREATE POLICY poshak_seva_anonymous_insert_policy ON poshak_seva_bookings
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- Policy for everyone to view all bookings (for demonstration purposes)
CREATE POLICY poshak_seva_select_policy ON poshak_seva_bookings
    FOR SELECT
    USING (true);

-- Policy for authenticated users to update bookings
CREATE POLICY poshak_seva_update_policy ON poshak_seva_bookings
    FOR UPDATE TO authenticated
    USING (true);
