// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efughnabhmwgqiftgigs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdWdobmFiaG13Z3FpZnRnaWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTU0MjMsImV4cCI6MjA2MTA5MTQyM30.H7HirCrxulLAZjTk1h330_JeSd0ql9wYifgRGpjHI3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);